services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YWhE3=58Yj3az#BP
      - MYSQL_DATABASE=unihub
    ports:
      - "3306:3306"
  app:
    depends_on:
      - mysqldb
    build: /
    restart: always
    ports:
      - "8443:8443"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/unihub?useSSL=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "YWhE3=58Yj3az#BP",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    stdin_open: true
    tty: true