version: "3.9"
services:
    web:
      image: ivansanchez22/unihub:v1.0
      ports:
        - "8443:8443"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3307/unihub
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=YWhE3=58Yj3az#BP
        - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      depends_on:
        - db
      restart: on-failure
    db:
      image: mysql:8.0
      container_name: db
      environment:
        - MYSQL_ROOT_PASSWORD=YWhE3=58Yj3az#BP
        - MYSQL_DATABASE=unihub
      ports:
        - "3307:3306"
    
    


