FROM node:16 AS angular
WORKDIR /code
COPY Angular-SPA/package*.json Angular-SPA/angular.json Angular-SPA/tsconfig*.json /code/
RUN npm install --legacy-peer-deps
COPY Angular-SPA/src /code/src
RUN npm run build -- --configuration production --base-href=/new/


FROM maven:3.6.3-openjdk-17 as builder
COPY Backend/UniHub/src/ /usr/src/app/src
COPY Backend/UniHub/pom.xml /usr/src/app
COPY --from=angular /code/dist/angular-spa /project/src/main/resources/static/new
WORKDIR /usr/src/app
RUN mvn package -DskipTests=true

FROM openjdk:17
COPY --from=builder /usr/src/app/target/UniHub-0.0.1-SNAPSHOT.jar /usr/src/
WORKDIR /usr/src
EXPOSE 8443
CMD ["java","-jar","UniHub-0.0.1-SNAPSHOT.jar"]

