FROM node:16 AS angular
WORKDIR /code
COPY Angular-SPA/package*.json Angular-SPA/angular.json Angular-SPA/tsconfig*.json /code/
RUN npm install --legacy-peer-deps
COPY Angular-SPA/src /code/src
RUN npm run build -- --configuration production --base-href=/new/

FROM maven:3.6.3-openjdk-17 as builder
WORKDIR /project
COPY Backend/UniHub/pom.xml /project/
COPY Backend/UniHub/src /project/src
COPY --from=angular /code/dist /project/src/main/resources/static/new
RUN mvn package

FROM openjdk:17
COPY Backend/UniHub/src/main/resources/static/img/Profile-Pics /usr/src/src/main/resources/static/img/Profile-Pics
COPY --from=builder /project/target/UniHub-0.0.1-SNAPSHOT.jar /usr/src/
WORKDIR /usr/src
EXPOSE 8443
CMD ["java","-jar","UniHub-0.0.1-SNAPSHOT.jar"]


