version: "3.9"
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YWhE3=58Yj3az#BP
      - MYSQL_DATABASE=unihub
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    image: ivansanchez22/unihub:v1.0
    depends_on:
      - mysqldb
    restart: always
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3307/unihub
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=YWhE3=58Yj3az#BP
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop


